<template>
  <div class="step">
    <p>
      To get an extraction of all your friend's birthdays from Facebook, you can
      use this wonderful Chrome extension:<br />
      <a
        target="_blank"
        href="https://chrome.google.com/webstore/detail/birthday-calendar-extract/imielmggcccenhgncmpjlehemlinhjjo"
        >Birthday Calendar Extractor for Facebook</a
      ><br /><br />
      The creator did an awesome job writing an open-source script that gets you
      the file you need to import the birthdays into your calendar. However, the
      file will include the birthdays of your whole friend list. If you want all
      the birthdays, use the file generated by the extension. If you would like
      to make a selection or make adjustments to the event titles or
      descriptions, continue following the next steps.
    </p>
  </div>
</template>

<script>
export default {}
</script>

<style lang="less" scoped>
.step {
  display: flex;
  justify-content: center;
  align-items: center;
  text-align: center;
  height: 100%;
  padding: 0 15%;
}
</style>
